server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aws?serverTimezone=JST
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML

